name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          go build main.go
          ./main &

      - name: Check health
        run: |
          sleep 5
          curl -X GET http://localhost:8080/health
          if [ $? -ne 0 ]; then
            echo "Application is unhealthy"
            ./rollback.sh
          fi